### ISSUE TITLE
Selecting the Root-Node leads to Exception

### ISSUE THREAD

**Issue by DrillSergeant** [sandstorm/NeosAcl#11]
When you create a dynamic role and select no nodes that role has access to all nodes, even if it is not stated in the UI like "Leave empty to grant access to all nodes".
I (my project team) thought it is easier to understand that a role has access to all nodes if we check the root-node (instead of checking no node at all).
After we did that (checked the root node and saved) we encoutered a bug:

**Steps to reproduce**
- Create a dynamic role
- Select the root-node and save the role
- Try to edit the role again

**Expected behaviour**
You can edit the role and the root-node is selected

**Actual behaviour**
You cannot edit the role, you end up in an exception.

Bug locally already fixed, PR will follow (in a few minutes...)

**Comment by skurfuerst** [comment]
thank you so much :)
